# Site settings
title: Thuvarakan Sritharan blog
description: "Research and Engineering Notes"
baseurl: ""
url: "https://thuva9872.github.io"
github_username: thuva9872

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge